language: c
compiler:
  - gcc
  - clang-3.8

sudo: required
dist: trusty

addons:
  apt:
    packages:
    - cmake
    - libp11-kit-dev
    - liburiparser-dev
    - clang-3.8

install:
  - wget https://downloads.sourceforge.net/project/ibmswtpm2/ibmtpm974.tar.gz
  - sha256sum ibmtpm974.tar.gz | grep -q 8e45d86129a0adb95fee4cee51f4b1e5b2d81ed3e55af875df53f98f39eb7ad7
  - mkdir ibmtpm974
  - pushd ibmtpm974 && tar axf ../ibmtpm974.tar.gz && pushd ./src && make
  - ./tpm_server &
  - popd && popd
  - wget http://ftpmirror.gnu.org/autoconf-archive/autoconf-archive-2017.09.28.tar.xz
  - sha256sum autoconf-archive-2017.09.28.tar.xz | grep -q 5c9fb5845b38b28982a3ef12836f76b35f46799ef4a2e46b48e2bd3c6182fa01
  - tar xJf autoconf-archive-2017.09.28.tar.xz && pushd autoconf-archive-2017.09.28
  - ./configure --prefix=/usr && make -j$(nproc) && sudo make install
  - popd
  - git clone https://github.com/tpm2-software/tpm2-tss.git
  - pushd tpm2-tss
  - ./bootstrap && ./configure && make -j$(nproc)
  - sudo make install
  - popd
  - sudo ldconfig /usr/local/lib
  - git clone https://github.com/tpm2-software/tpm2-abrmd.git
  - pushd tpm2-abrmd
  - ./bootstrap && ./configure --with-dbuspolicydir=/etc/dbus-1/system.d
  - make -j$(nproc) && sudo make install
  - popd
  - sudo mkdir -p /var/lib/tpm
  - sudo groupadd tss && sudo useradd -M -d /var/lib/tpm -s /bin/false -g tss tss
  - sudo pkill -HUP dbus-daemon
  - sudo -u tss tpm2-abrmd --tcti=socket &

script:
  - mkdir build
  - pushd build
  - cmake .. && make
